import * as json from "../../json/types";

// File like https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb
/** The last known iOS SDK (stable). */
export const LAST_KNOWN_IOS_SDK = "18.0";

/** The last known macOS SDK (stable). */
export const LAST_KNOWN_OSX_SDK = "15.0";

/** The last known tvOS SDK (stable). */
export const LAST_KNOWN_TVOS_SDK = "18.0";

/** The last known visionOS SDK (unstable). */
export const LAST_KNOWN_VISIONOS_SDK = "2.0";

/** The last known watchOS SDK (stable). */
export const LAST_KNOWN_WATCHOS_SDK = "11.0";

/** The last known archive version to Xcodeproj. */
export const LAST_KNOWN_ARCHIVE_VERSION = 1;

/** The last known Swift version (stable). */
export const LAST_KNOWN_SWIFT_VERSION = "5.0";

/** The default object version for Xcodeproj. */
export const DEFAULT_OBJECT_VERSION = 46;

/** The last known object version to Xcodeproj. */
export const LAST_KNOWN_OBJECT_VERSION = 77;

/** The last known Xcode version to Xcodeproj. */
export const LAST_UPGRADE_CHECK = "1600";

/** The last known Swift upgrade version to Xcodeproj. */
export const LAST_SWIFT_UPGRADE_CHECK = "1600";

/**
 * The known file types corresponding to each extension.
 *
 * Derived from Xcode's built-in file type specs:
 * - DevToolsCore.framework/Versions/A/Resources/BuiltInFileTypes.xcspec
 * - DevToolsCore.framework/Versions/A/Resources/StandardFileTypes.xcspec
 * - Core Data.xcplugin/Contents/Resources/Core Data.pbfilespec
 * - CoreBuildTasks.xcplugin/Contents/Resources/InstrumentsPackage.xcspec
 * - Intents.xcplugin/Contents/Resources/Intents.pbfilespec
 * - Metal.xcplugin/Contents/Resources/FileTypes.xcspec
 * - RCBuildSystemSupport.xcplugin/Contents/Resources/RCFileTypes.pbfilespec
 * - SceneKit.xcplugin/Contents/Resources/SceneKit FileTypes.xcspec
 * - SpriteKit.xcplugin/Contents/Resources/SpriteKitFileTypes.xcspec
 * - XCLanguageSupport.xcplugin/Contents/Resources/Swift.pbfilespec
 */
export const FILE_TYPES_BY_EXTENSION: Record<string, json.FileType> =
  Object.freeze({
    "1": "text.man",
    C: "sourcecode.cpp.cpp",
    H: "sourcecode.cpp.h",
    M: "sourcecode.cpp.objcpp",
    a: "archive.ar",
    ada: "sourcecode.ada",
    adb: "sourcecode.ada",
    ads: "sourcecode.ada",
    aiff: "audio.aiff",
    air: "compiled.air",
    apinotes: "text.apinotes",
    apns: "text",
    app: "wrapper.application",
    // NOTE: This could also be `wrapper.extensionkit-extension`
    appex: "wrapper.app-extension",
    applescript: "sourcecode.applescript",
    archivingdescription: "text.xml.ibArchivingDescription",
    asdictionary: "archive.asdictionary",
    asm: "sourcecode.asm.asm",
    atlas: "folder.skatlas",
    au: "audio.au",
    avi: "video.avi",
    bazel: "text.script.python",
    bin: "archive.macbinary",
    bmp: "image.bmp",
    bundle: "wrapper.cfbundle",
    bzl: "text.script.python",
    c: "sourcecode.c.c",
    "c++": "sourcecode.cpp.cpp",
    cc: "sourcecode.cpp.cpp",
    cdda: "audio.aiff",
    cl: "sourcecode.opencl",
    class: "compiled.javaclass",
    classdescription: "text.plist.ibClassDescription",
    classdescriptions: "text.plist.ibClassDescription",
    clp: "sourcecode.clips",
    cp: "sourcecode.cpp.cpp",
    cpp: "sourcecode.cpp.cpp",
    csh: "text.script.csh",
    css: "text.css",
    ctrl: "sourcecode.glsl",
    cxx: "sourcecode.cpp.cpp",
    d: "sourcecode.dtrace",
    dSYM: "wrapper.dsym",
    dae: "text.xml.dae",
    defs: "sourcecode.mig",
    dext: "wrapper.driver-extension",
    dict: "text.plist",
    docc: "folder.documentationcatalog",
    dsym: "wrapper.dsym",
    dtd: "text.xml",
    dylan: "sourcecode.dylan",
    dylib: "compiled.mach-o.dylib",
    ear: "archive.ear",
    entitlements: "text.plist.entitlements",
    eval: "sourcecode.glsl",
    exp: "sourcecode.exports",
    f: "sourcecode.fortran",
    f77: "sourcecode.fortran.f77",
    f90: "sourcecode.fortran.f90",
    f95: "sourcecode.fortran.f90",
    for: "sourcecode.fortran",
    frag: "sourcecode.glsl",
    fragment: "sourcecode.glsl",
    framework: "wrapper.framework",
    fs: "sourcecode.glsl",
    fsh: "sourcecode.glsl",
    geom: "sourcecode.glsl",
    geometry: "sourcecode.glsl",
    gif: "image.gif",
    gmk: "sourcecode.make",
    gpx: "text.xml",
    gs: "sourcecode.glsl",
    gsh: "sourcecode.glsl",
    gz: "archive.gzip",
    h: "sourcecode.c.h",
    "h++": "sourcecode.cpp.h",
    hh: "sourcecode.cpp.h",
    hp: "sourcecode.cpp.h",
    hpp: "sourcecode.cpp.h",
    hqx: "archive.binhex",
    htm: "text.html",
    html: "text.html",
    htmld: "wrapper.htmld",
    hxx: "sourcecode.cpp.h",
    i: "sourcecode.c.c.preprocessed",
    icns: "image.icns",
    ico: "image.ico",
    iconset: "folder.iconset",
    ii: "sourcecode.cpp.cpp.preprocessed",
    iig: "sourcecode.iig",
    imagecatalog: "folder.imagecatalog",
    inc: "sourcecode.pascal",
    instrdst: "com.apple.instruments.instrdst",
    instrpkg: "com.apple.instruments.package-definition",
    intentdefinition: "file.intentdefinition",
    ipp: "sourcecode.cpp.h",
    jam: "sourcecode.jam",
    jar: "archive.jar",
    java: "sourcecode.java",
    javascript: "sourcecode.javascript",
    jpeg: "image.jpeg",
    jpg: "image.jpeg",
    js: "sourcecode.javascript",
    jscript: "sourcecode.javascript",
    json: "text.json",
    jsp: "text.html.other",
    kext: "wrapper.kernel-extension",
    l: "sourcecode.lex",
    lid: "sourcecode.dylan",
    ll: "sourcecode.asm.llvm",
    llx: "sourcecode.asm.llvm",
    lm: "sourcecode.lex",
    lmm: "sourcecode.lex",
    lp: "sourcecode.lex",
    lpp: "sourcecode.lex",
    lxx: "sourcecode.lex",
    m: "sourcecode.c.objc",
    mak: "sourcecode.make",
    make: "sourcecode.make",
    map: "sourcecode.module-map",
    markdown: "net.daringfireball.markdown",
    md: "net.daringfireball.markdown",
    mdimporter: "wrapper.spotlight-importer",
    mdown: "net.daringfireball.markdown",
    metal: "sourcecode.metal",
    metallib: "archive.metal-library",
    mi: "sourcecode.c.objc.preprocessed",
    mid: "audio.midi",
    midi: "audio.midi",
    mig: "sourcecode.mig",
    mii: "sourcecode.cpp.objcpp.preprocessed",
    mlkitmodel: "file.mlmodel",
    mlmodel: "file.mlmodel",
    mm: "sourcecode.cpp.objcpp",
    modulemap: "sourcecode.module-map",
    moov: "video.quicktime",
    mov: "video.quicktime",
    mp3: "audio.mp3",
    mpeg: "video.mpeg",
    mpg: "video.mpeg",
    mpkg: "wrapper.installer-mpkg",
    nasm: "sourcecode.nasm",
    nib: "wrapper.nib",
    "nib~": "wrapper.nib",
    nqc: "sourcecode.nqc",
    o: "compiled.mach-o.objfile",
    octest: "wrapper.cfbundle",
    otf: "file",
    p: "sourcecode.pascal",
    pas: "sourcecode.pascal",
    pbfilespec: "text.plist.pbfilespec",
    pblangspec: "text.plist.pblangspec",
    pbxproj: "text.pbxproject",
    pch: "sourcecode.c.h",
    "pch++": "sourcecode.cpp.h",
    pct: "image.pict",
    pdf: "image.pdf",
    perl: "text.script.perl",
    php: "text.script.php",
    php3: "text.script.php",
    php4: "text.script.php",
    phtml: "text.script.php",
    pict: "image.pict",
    pkg: "wrapper.installer-pkg",
    pl: "text.script.perl",
    playground: "file.playground",
    plist: "text.plist",
    pluginkit: "wrapper.app-extension",
    pm: "text.script.perl",
    png: "image.png",
    pp: "sourcecode.pascal",
    ppob: "archive.ppob",
    proto: "sourcecode.protobuf",
    py: "text.script.python",
    qtz: "video.quartz-composer",
    r: "sourcecode.rez",
    rb: "text.script.ruby",
    rbw: "text.script.ruby",
    rcproject: "file.rcproject",
    rcx: "compiled.rcx",
    rez: "sourcecode.rez",
    rhtml: "text.html.other",
    rsrc: "archive.rsrc",
    rtf: "text.rtf",
    rtfd: "wrapper.rtfd",
    s: "sourcecode.asm",
    scnassets: "wrapper.scnassets",
    scncache: "wrapper.scncache",
    scnp: "file.scp",
    scriptSuite: "text.plist.scriptSuite",
    scriptTerminology: "text.plist.scriptTerminology",
    sh: "text.script.sh",
    shtml: "text.html.other",
    sit: "archive.stuffit",
    sks: "file.sks",
    skybox: "file.skybox",
    sqlite: "file",
    storyboard: "file.storyboard",
    storyboardc: "wrapper.storyboardc",
    strings: "text.plist.strings",
    stringsdict: "text.plist.stringsdict",
    swift: "sourcecode.swift",
    systemextension: "wrapper.system-extension",
    tar: "archive.tar",
    tbd: "sourcecode.text-based-dylib-definition",
    tcc: "sourcecode.cpp.cpp",
    text: "net.daringfireball.markdown",
    tif: "image.tiff",
    tiff: "image.tiff",
    ttf: "file",
    txt: "text",
    uicatalog: "file.uicatalog",
    usdz: "file.usdz",
    vert: "sourcecode.glsl",
    vertex: "sourcecode.glsl",
    view: "archive.rsrc",
    vs: "sourcecode.glsl",
    vsh: "sourcecode.glsl",
    war: "archive.war",
    wav: "audio.wav",
    worksheet: "text.script.worksheet",
    xcassets: "folder.assetcatalog",
    xcbuildrules: "text.plist.xcbuildrules",
    xcclassmodel: "wrapper.xcclassmodel",
    xcconfig: "text.xcconfig",
    xcdatamodel: "wrapper.xcdatamodel",
    xcdatamodeld: "wrapper.xcdatamodeld",
    xcfilelist: "text.xcfilelist",
    xcframework: "wrapper.xcframework",
    xclangspec: "text.plist.xclangspec",
    xcmappingmodel: "wrapper.xcmappingmodel",
    xcode: "wrapper.pb-project",
    xcodeproj: "wrapper.pb-project",
    xconf: "text.xml",
    xcplaygroundpage: "file.xcplaygroundpage",
    xcspec: "text.plist.xcspec",
    xcstickers: "folder.stickers",
    xcsynspec: "text.plist.xcsynspec",
    xctarget: "wrapper.pb-target",
    xctest: "wrapper.cfbundle",
    xctxtmacro: "text.plist.xctxtmacro",
    xcworkspace: "wrapper.workspace",
    xhtml: "text.xml",
    xib: "file.xib",
    xmap: "text.xml",
    xml: "text.xml",
    xpc: "wrapper.xpc-service",
    xsl: "text.xml",
    xslt: "text.xml",
    xsp: "text.xml",
    y: "sourcecode.yacc",
    yaml: "text.yaml",
    ym: "sourcecode.yacc",
    yml: "text.yaml",
    ymm: "sourcecode.yacc",
    yp: "sourcecode.yacc",
    ypp: "sourcecode.yacc",
    yxx: "sourcecode.yacc",
    zip: "archive.zip",
  });

export const PRODUCT_UTI_EXTENSIONS = Object.freeze({
  application: "app",
  applicationOnDemandInstallCapable: "app",
  framework: "framework",
  dynamicLibrary: "dylib",
  staticLibrary: "a",
  bundle: "bundle",
  octestBundle: "octest",
  unitTestBundle: "xctest",
  uiTestBundle: "xctest",
  appExtension: "appex",
  messagesApplication: "app",
  messagesExtension: "appex",
  stickerPack: "appex",
  watch2Extension: "appex",
  watch2App: "app",
  watch2AppContainer: "app",
});

export const SOURCETREE_BY_FILETYPE: Record<string, json.SourceTree> =
  Object.freeze({
    "compiled.mach-o.dylib": "SDKROOT",
    "sourcecode.text-based-dylib-definition": "SDKROOT",
    "wrapper.framework": "SDKROOT",
    "wrapper.app-extension": "BUILT_PRODUCTS_DIR",
    "wrapper.extensionkit-extension": "BUILT_PRODUCTS_DIR",
  });

export const PROJECT_DEFAULT_BUILD_SETTINGS = Object.freeze({
  all: Object.freeze({
    ALWAYS_SEARCH_USER_PATHS: "NO",
    CLANG_ANALYZER_NONNULL: "YES",
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE",
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++14",
    CLANG_CXX_LIBRARY: "libc++",
    CLANG_ENABLE_MODULES: "YES",
    CLANG_ENABLE_OBJC_ARC: "YES",
    CLANG_ENABLE_OBJC_WEAK: "YES",
    CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES",
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES",
    CLANG_WARN_BOOL_CONVERSION: "YES",
    CLANG_WARN_COMMA: "YES",
    CLANG_WARN_CONSTANT_CONVERSION: "YES",
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES",
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR",
    CLANG_WARN_DOCUMENTATION_COMMENTS: "YES",
    CLANG_WARN_EMPTY_BODY: "YES",
    CLANG_WARN_ENUM_CONVERSION: "YES",
    CLANG_WARN_INFINITE_RECURSION: "YES",
    CLANG_WARN_INT_CONVERSION: "YES",
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES",
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES",
    CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES",
    CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR",
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: "YES",
    CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES",
    CLANG_WARN_STRICT_PROTOTYPES: "YES",
    CLANG_WARN_SUSPICIOUS_MOVE: "YES",
    CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE",
    CLANG_WARN_UNREACHABLE_CODE: "YES",
    COPY_PHASE_STRIP: "NO",
    ENABLE_STRICT_OBJC_MSGSEND: "YES",
    GCC_C_LANGUAGE_STANDARD: "gnu11",
    GCC_NO_COMMON_BLOCKS: "YES",
    GCC_WARN_64_TO_32_BIT_CONVERSION: "YES",
    GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR",
    GCC_WARN_UNDECLARED_SELECTOR: "YES",
    GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE",
    GCC_WARN_UNUSED_FUNCTION: "YES",
    GCC_WARN_UNUSED_VARIABLE: "YES",
    MTL_FAST_MATH: "YES",
    PRODUCT_NAME: "$(TARGET_NAME)",
    SWIFT_VERSION: "5.0",
  } as const),
  release: Object.freeze({
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym",
    ENABLE_NS_ASSERTIONS: "NO",
    MTL_ENABLE_DEBUG_INFO: "NO",
    SWIFT_COMPILATION_MODE: "wholemodule",
    SWIFT_OPTIMIZATION_LEVEL: "-O",
  } as const),
  debug: Object.freeze({
    DEBUG_INFORMATION_FORMAT: "dwarf",
    ENABLE_TESTABILITY: "YES",
    GCC_DYNAMIC_NO_PIC: "NO",
    GCC_OPTIMIZATION_LEVEL: "0",
    GCC_PREPROCESSOR_DEFINITIONS: ["DEBUG=1", "$(inherited)"],
    MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE",
    ONLY_ACTIVE_ARCH: "YES",
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG",
    SWIFT_OPTIMIZATION_LEVEL: "-Onone",
  } as const),
} as const);
